server:
  port: 8082
spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: true
        
zuul:
  ignored-services:
  - '*'
  sensitive-headers:
  - Cookie,Set-Cookie
  routes:
    oauth2-service:
      path: /auth-service/**
      url: http://localhost:9191/auth-service
    resource-service:
      path: /resource-server/**
      #url: http://localhost:8081/resource-server
      serviceId: resource-service
      stripPrefix: true