server:
  servlet:
    context-path: /microservice1
    
spring:
  zipkin:
    base-url: http://localhost:9411/
    
    
  application:
    name: microservice1
    
  servlet:
    multipart:
      enabled: true
      location: D:\Dinesh\Others\multipart\
      max-file-size:
        10MB
      max-request-size:
        15MB
