server:
  port: 8081
  servlet:
    context-path: /resource-server
spring:
  application:
    name: resource-service

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9191/auth-service/oauth/check_token
    client:
      client-id: agency
      client-secret: agency
     