server:
  port: 8081
  servlet:
    context-path: /sparktg-test-app
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  
security:
  oauth2:
    client:
      client-id: client
      client-secret: secret

    

