server:
  port: 8888
  servlet:
    session:
      cookie:
        name: KSESSION 
  
security:
  oauth2:
    client:
      client-id: agency
      client-secret: agency
      user-authorization-uri: http://localhost:9191/auth-service/oauth/authorize
      access-token-uri: http://localhost:9191/auth-service/oauth/token
    resource:
      token-info-uri: http://localhost:9191/auth-service/oauth/check_token
      
