apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-my-first-cluster-1
  labels:
    app: docker-my-first-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-my-first-cluster
  template:
    metadata:
      labels:
        app: docker-my-first-cluster
    spec:
      containers:
      - name: docker-my-first-cluster
        image: dgangwar14/docker-demo-service
        ports:
        - containerPort: 8080